name: schemani_formini
description: Validate formini using schemani
version: 0.0.1-alpha.1
author: Jari Pekkala <jari@vantage.fi>
homepage: https://vantage.fi

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  schemani:
    git: git://github.com/vantageoy/schemani.git
  formini:
    git: git://github.com/vantageoy/formini.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
