name: schemani_formini
description: Validate formini using schemani
version: 0.0.1-alpha.1
author: Jari Pekkala <jari@vantage.fi>
homepage: https://github.com/vantageoy/schemani_formini

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  schemani: ^0.0.1-alpha
  formini: ^0.0.1-alpha

dev_dependencies:
  flutter_test:
    sdk: flutter
